import os
import sqlite3
from datetime import datetime

DB_PATH = os.path.join(os.path.dirname(__file__), "rng.db")


# initiates db if necessary
def _connect() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON")
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS sessions (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            source          TEXT NOT NULL,
            created_at      TEXT NOT NULL,
            gen_exec_time   REAL,
            audit_exec_time REAL
        );

        CREATE TABLE IF NOT EXISTS bit_data (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            byte       INTEGER NOT NULL,
            session_id INTEGER NOT NULL REFERENCES sessions(id)
        );

        CREATE TABLE IF NOT EXISTS audit_data (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            basis      TEXT NOT NULL,
            outcome    INTEGER NOT NULL,
            count      INTEGER NOT NULL,
            session_id INTEGER NOT NULL REFERENCES sessions(id)
        );
        """
    )
    return conn


# stores session in dataase
def storeSession(source: str, gen_exec_time: float, audit_exec_time: float | None = None) -> int:
    conn = _connect()
    with conn:
        cur = conn.execute(
            "INSERT INTO sessions (source, created_at, gen_exec_time, audit_exec_time) VALUES (?, ?, ?, ?)",
            (source, datetime.now().isoformat(timespec="seconds"), gen_exec_time, audit_exec_time),
        )
        session_id = cur.lastrowid
    conn.close()
    return session_id


# stores generated bytes in database
def storeBytes(data: bytes, session_id: int) -> None:
    conn = _connect()
    with conn:
        conn.executemany(
            "INSERT INTO bit_data (byte, session_id) VALUES (?, ?)",
            [(int(b), session_id) for b in data],
        )
    conn.close()


# stores data related to self-testing
def storeAudit(rows: list[tuple[str, int, int]], session_id: int) -> None:
    conn = _connect()
    with conn:
        conn.executemany(
            "INSERT INTO audit_data (basis, outcome, count, session_id) VALUES (?, ?, ?, ?)",
            [(basis, int(outcome), int(count), session_id) for basis, outcome, count in rows],
        )
    conn.close()


# returns session information
def getSession(session_id: int) -> dict | None:
    conn = _connect()
    with conn:
        row = conn.execute(
            "SELECT id, source, created_at, gen_exec_time, audit_exec_time FROM sessions WHERE id = ?",
            (session_id,),
        ).fetchone()
    conn.close()
    if row is None:
        return None
    return {
        "id": row[0],
        "source": row[1],
        "created_at": row[2],
        "gen_exec_time": row[3],
        "audit_exec_time": row[4],
    }


# returns generated bytes of a session
def getBytes(session_id: int | None = None) -> list[int]:
    conn = _connect()
    with conn:
        if session_id is None:
            rows = conn.execute("SELECT byte FROM bit_data ORDER BY id").fetchall()
        else:
            rows = conn.execute(
                "SELECT byte FROM bit_data WHERE session_id = ? ORDER BY id",
                (session_id,),
            ).fetchall()
    conn.close()
    return [row[0] for row in rows]



# returns the number of output bytes stored in a session.
def countBytes(session_id: int) -> int:
    conn = _connect()
    with conn:
        row = conn.execute(
            "SELECT count(*) FROM bit_data WHERE session_id = ?",
            (session_id,),
        ).fetchone()
    conn.close()
    return row[0]
