import os
import sqlite3
from datetime import datetime
from typing import List, Tuple

DB_PATH = os.path.join(os.path.dirname(__file__), "rng.db")

# Automatically extract rng.zip if rng.db is missing but the zip is available
if not os.path.exists(DB_PATH):
    zip_path = os.path.join(os.path.dirname(__file__), "rng.zip")
    if os.path.exists(zip_path):
        import zipfile
        try:
            with zipfile.ZipFile(zip_path, "r") as zip_ref:
                zip_ref.extractall(os.path.dirname(__file__))
            print("Extracted rng.db from rng.zip successfully.")
        except Exception as e:
            print(f"Warning: Failed to extract rng.zip: {e}")


# initiates db if necessary
def _connect() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON")
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS sessions (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            source          TEXT NOT NULL,
            created_at      TEXT NOT NULL,
            gen_exec_time   REAL,
            audit_exec_time REAL,
            chsh_score      REAL,
            is_simulation   INTEGER NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS bit_data (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            byte       INTEGER NOT NULL,
            session_id INTEGER NOT NULL REFERENCES sessions(id)
        );

        CREATE TABLE IF NOT EXISTS audit_data (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            basis      TEXT NOT NULL,
            outcome    INTEGER NOT NULL,
            count      INTEGER NOT NULL,
            session_id INTEGER NOT NULL REFERENCES sessions(id)
        );
        """
    )
    return conn


# stores session in dataase
def storeSession(source: str, gen_exec_time: float, audit_exec_time: float | None = None, chsh_score: float | None = None, is_simulation: bool = False) -> int:
    conn = _connect()
    with conn:
        cur = conn.execute(
            "INSERT INTO sessions (source, created_at, gen_exec_time, audit_exec_time, chsh_score, is_simulation) VALUES (?, ?, ?, ?, ?, ?)",
            (source, datetime.now().isoformat(timespec="seconds"), gen_exec_time, audit_exec_time, chsh_score, int(is_simulation)),
        )
        session_id = cur.lastrowid
    conn.close()
    return session_id


# stores generated bytes in database
def storeBytes(data: bytes, session_id: int) -> None:
    conn = _connect()
    with conn:
        conn.executemany(
            "INSERT INTO bit_data (byte, session_id) VALUES (?, ?)",
            [(int(b), session_id) for b in data],
        )
    conn.close()


# stores data related to self-testing
def storeAudit(rows: list[tuple[str, int, int]], session_id: int) -> None:
    conn = _connect()
    with conn:
        conn.executemany(
            "INSERT INTO audit_data (basis, outcome, count, session_id) VALUES (?, ?, ?, ?)",
            [(basis, int(outcome), int(count), session_id) for basis, outcome, count in rows],
        )
    conn.close()


# returns session information
def getSession(session_id: int) -> dict | None:
    conn = _connect()
    with conn:
        row = conn.execute(
            "SELECT id, source, created_at, gen_exec_time, audit_exec_time, chsh_score, is_simulation FROM sessions WHERE id = ?",
            (session_id,),
        ).fetchone()
    conn.close()
    if row is None:
        return None
    return {
        "id": row[0],
        "source": row[1],
        "created_at": row[2],
        "gen_exec_time": row[3],
        "audit_exec_time": row[4],
        "chsh_score": row[5],
        "is_simulation": bool(row[6]),
    }


# returns generated bytes of a session
def getBytes(session_id: int | None = None) -> list[int]:
    conn = _connect()
    with conn:
        if session_id is None:
            rows = conn.execute("SELECT byte FROM bit_data ORDER BY id").fetchall()
        else:
            rows = conn.execute(
                "SELECT byte FROM bit_data WHERE session_id = ? ORDER BY id",
                (session_id,),
            ).fetchall()
    conn.close()
    return [row[0] for row in rows]

# returns audit data of sessions
def getAuditDataForSessions(session_ids: List[int]) -> List[Tuple[str, int, int]]:
    conn = _connect()
    with conn:
        placeholders = ",".join("?" for _ in session_ids)
        query = f"SELECT basis, outcome, count FROM audit_data WHERE session_id IN ({placeholders})"
        rows = conn.execute(query, session_ids).fetchall()
    conn.close()
    return rows

# returns session ids for specific rng
def getSessionIDsBySource(source: str, simulated: bool = False) -> List[int]:

    conn = _connect()
    with conn:
        rows = conn.execute(
            "SELECT id FROM sessions WHERE source = ? AND is_simulation = ?",
            (source, int(simulated)),
        ).fetchall()
    conn.close()
    return [row[0] for row in rows]


# returns the number of output bytes stored in a session.
def countBytes(session_id: int) -> int:
    conn = _connect()
    with conn:
        row = conn.execute(
            "SELECT count(*) FROM bit_data WHERE session_id = ?",
            (session_id,),
        ).fetchone()
    conn.close()
    return row[0]


# returns duration of a session, or all sessions
def getDuration(session_id: int | None = None) -> float:
    conn = _connect()
    with conn:
        if session_id is None:
            row = conn.execute(
                "SELECT SUM(gen_exec_time), SUM(audit_exec_time) FROM sessions WHERE is_simulation = 0"
            ).fetchone()
        else:
            row = conn.execute(
                "SELECT gen_exec_time, audit_exec_time FROM sessions WHERE id = ?",
                (session_id,),
            ).fetchone()
    conn.close()
    if row is None:
        return 0.0
    gen_exec_time, audit_exec_time = row
    total_duration = gen_exec_time or 0.0
    if audit_exec_time is not None:
        total_duration += audit_exec_time
    return total_duration
